import type { Metadata } from "next";
import { Amiri } from "next/font/google";
import "./globals.css";

const amiri = Amiri({
  subsets: ["arabic"],
  variable: "--amiri",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Sheikh Othman Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${amiri.className} antialiased`}>{children}</body>
    </html>
  );
}
